version: '3.2'
services:
  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD
    volumes:
    - ./database/fixture.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "$PORT:$PORT"
    depends_on:
      - db
    environment: 
      - PORT
    command: "-port=$PORT -db_name=$POSTGRES_DB -db_host=db -db_user=$POSTGRES_USER"